AWSTemplateFormatVersion: "2010-09-09"
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  Lambda:
    Type: 'AWS::Serverless::Function'
     # the 2 policies below should satisfy cfn-lint but the SAM transform isn't passing them thru apparently
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      FunctionName: new_release_twitter
      Handler: index.handler
      Runtime: nodejs12.x
      CodeUri: ./src
      AutoPublishAlias: live
      Description: Lambda that emails me relevant tweets
      Role: !GetAtt [ LambdaExecutionRole, Arn ]
      MemorySize: 192
      Timeout: 900

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      Policies:
        -
          PolicyName: SendEmail
          PolicyDocument:
            Statement:
              -
                Action:
                  - ses:SendEmail
                  - ses:SendRawEmail
                Resource: 
                  - "*"
                Effect: Allow
        -
          PolicyName: CreateLogs
          PolicyDocument:
            Statement:
              -
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: 
                  - "*"
                Effect: Allow

      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com

